Add RST file for kopt module
theochem/procrustes pull request #58
Opened 2021-03-05 02:49 UTC by fwmeng88

- [ ] Add rst file for kopt module and update api_index.rst.

2021-03-05 18:03 UTC, FarnazH requested changes

2021-03-05 18:03 UTC, FarnazH commented on docs/api/kopt.rst
> +    : Copyright (C) 2017-2020 The Procrustes Development Team
The HEADER should be updated.

2021-03-05 19:15 UTC, fwmeng88 commented on docs/api/kopt.rst
> +    : Copyright (C) 2017-2020 The Procrustes Development Team
This problem is addressed at 5ebb46c.

2021-03-05 19:15 UTC, fwmeng88 commented
I also removed a useless file in e120bdd.

2021-03-06 00:55 UTC, FarnazH approved these changes

2021-03-06 00:55 UTC, merged